### ISSUE TITLE
Better Application Icon

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/clairvoyant#1]
Yep, need 'em. I'm thinking either a :8ball: or a :crystal_ball:.

**Comment by cassidyjames** [comment]
Leaving this open since the current icon could use some work :joy:

**Comment by eljefuri** [comment]
Yes, "?" seems a bit like a help button. Which is in a sense true. :-)

**Comment by cassidyjames** [comment]
@eljefuri this issue is about the technical execution of the application icon itself, not the clarity of in-app icons.

**Comment by cassidyjames** [comment]
Fixed by #30
