### ISSUE TITLE
Appdata isn't translated

### ISSUE THREAD

**Issue by NathanBnm** [cassidyjames/clairvoyant#13]
It doesn't appear translated in the AppCenter. Maybe there is an issue with build.

**Comment by cassidyjames** [comment]
I can't reproduce this in GNOME Software when using the AppCenter or Flathub remotes.

![Screenshot from 2022-09-27 21-25-02](https://user-images.githubusercontent.com/611168/192680636-f6b2b9f8-dc23-412d-a1f4-d5f1b0e85dad.png)
![Screenshot from 2022-09-27 21-25-09](https://user-images.githubusercontent.com/611168/192680640-2bedfd99-221d-46ac-a255-4258da419bbd.png)
