### ISSUE TITLE
Add more replies

### ISSUE THREAD

**Issue by kdwk** [cassidyjames/clairvoyant#28]
The Magic 8 Ball sounds a tiny bit repetitive. Adding more responses would make it more enjoyable

**Comment by kdwk** [comment]
I'm working for a PR for this (since it's a pretty easy task), but I don't want to install dev libraries on my main machine, so I have to wait till I test it in a VM

**Comment by cassidyjames** [comment]
@kdwk the responses are inspired by a real magic 8 ball; I'm not opposed to adding more, but I think I'd like to keep the same ratio of positive, negative, and neutral responses.
