### ISSUE TITLE
No 8 in the ball

### ISSUE THREAD

**Issue by Gustavekkj** [cassidyjames/clairvoyant#3]
Hi when the app launches there is no 8 or white circle on the icon in dock. On elementary Juno beta. 
![no 8 in ball](https://user-images.githubusercontent.com/31554493/43063745-fe5a386c-8e5c-11e8-8ad3-8183fe7702cc.png)

**Comment by cassidyjames** [comment]
Hm, it looks like somehow the 48px icon got missed. I'll get that fixed!

**Comment by cassidyjames** [comment]
Fixed in a670a03df3eee1a2be7ca1d765a5f4a6d53bfed8
