### ISSUE TITLE
Something happened to localizations?

### ISSUE THREAD

**Issue by Vovkiv** [cassidyjames/clairvoyant#60]
I got update for clairvoyant from flathub, run it, expecting to see newly added translation, but there none. I checked .po folder of project and it seems that all .po files were kinda "erased"? Is something happened or everything according to plans?

**Comment by cassidyjames** [comment]
@Vovkiv hm, no, it's possible I messed something up. I'll take a look!

**Comment by Vovkiv** [comment]
While Ukrainian translation was restored, make sure that others were as well, because they might be also affected

**Comment by cassidyjames** [comment]
@Vovkiv it should be resolved as of 3.1.3; let me know if that's not the case!
