### ISSUE TITLE
Custom window shape?

### ISSUE THREAD

**Issue by eljefuri** [cassidyjames/clairvoyant#7]
If it is possible in Elementary, why not make Clairvoyant actually look like a Magic 8-Ball? Note that in addition to any technical reason, the answer may be that that the design may or may not be subject to live [patents](https://en.wikipedia.org/wiki/Magic_8-Ball#Patents) (I have not researched this).

**Comment by cassidyjames** [comment]
I don't believe truly non-rectangular windows work correctly in X, so a circle could be problematic there. In addition, I don't know that I want to go super skeumorphic with Clairvoyant over a familiar/predictable window metaphor.

**Comment by cassidyjames** [comment]
I think I'm going to skip on this as a custom window shape seems both difficult and unexpected on the desktop
