### ISSUE TITLE
No question wording

### ISSUE THREAD

**Issue by Ricky-Tigg** [cassidyjames/clairvoyant#72]
**v. :** 3.1.2. **Gnome v.:** 45.2. **OS:** Fedora.

Hello. Without question wording*, clicking the _Ask again_ element is supported. and even a text is displayed as an answer; here it's a _Yep!_.

![flatpak_clairvoyant_v 3 1 2](https://github.com/cassidyjames/clairvoyant/assets/26058215/21da35af-ad94-4cda-97e4-5714d709fc49)

* And how could it be, since the interface is missing a field aimed at this purpose.

**Comment by cassidyjames** [comment]
The idea is the app is supposed to be like an old-school Magic 8-ball, so you think of a question and then open the app. :)

I could maybe add an empty state, but I like that you can just open the app and get an instant random answer without having to click anything. 🤔
