### ISSUE TITLE
Snap package for this app

### ISSUE THREAD

**Issue by soumyaDghosh** [cassidyjames/clairvoyant#74]
Hi, I have created a snap package for your app, would you like to take it as another official package?

**Comment by cassidyjames** [comment]
No, thank you. I don't have time or energy to maintain the app in multiple locations/formats and have explicitly chosen Flatpak. I'll make that more clear in the README. :)

**Comment by soumyaDghosh** [comment]
I am unoffically uploading the app in the store then? if you have no problem?

**Comment by cassidyjames** [comment]
@soumyaDghosh I would prefer not because that tends to lead to people reporting issues against my app that I can't reproduce or support.

**Comment by soumyaDghosh** [comment]
I have changed the bugtracker link to the snap manifest page, and have already clearly stated the snap as unofficial in the store.

https://github.com/soumyaDghosh/clairvoyant-snap/blob/main/snap/snapcraft.yaml#L22
