### ISSUE TITLE
Click the answer to shake

### ISSUE THREAD

**Issue by eljefuri** [cassidyjames/clairvoyant#9]
Because the [iconography is unclear](https://github.com/cassidyjames/clairvoyant/issues/1), the means of getting a new answer is a bit difficult to figure out. My intuitive attempt was clicking the answer itself to get a new one, and I do think that it should work this way in addition to whatever buttons or icons may come in the future.

**Comment by cassidyjames** [comment]
Fixed by an explicit button in #30
